import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

/**
 * ML Predictions API Endpoint
 * 
 * Returns ML model predictions from the Python backend.
 * Predictions are generated by running the ML forecasting module.
 */
export async function GET(request) {
    try {
        const { searchParams } = new URL(request.url);
        const region = searchParams.get('region') || 'SA1';
        const model = searchParams.get('model') || 'xgboost';

        // Try to load predictions from JSON file generated by Python
        const predictionsPath = path.join(process.cwd(), 'public', `predictions_${region}.json`);

        if (fs.existsSync(predictionsPath)) {
            const data = JSON.parse(fs.readFileSync(predictionsPath, 'utf8'));
            return NextResponse.json({
                predictions: data.predictions || [],
                model: data.model || model,
                accuracy: data.accuracy || null,
                region: region,
                source: 'Python ML Model',
                lastUpdated: data.lastUpdated || new Date().toISOString()
            });
        }

        // Fallback to simulation data if ML predictions not available
        const simPath = path.join(process.cwd(), 'public', `simulation_${region}.json`);

        if (fs.existsSync(simPath)) {
            const data = JSON.parse(fs.readFileSync(simPath, 'utf8'));

            // Extract forecast data from simulation if available
            const predictions = data.prices?.map(p => ({
                time: p.time,
                actual: p.price,
                predicted: p.forecast || p.price,
                signal: p.signal || 'hold'
            })) || [];

            return NextResponse.json({
                predictions,
                model: 'ema_forecast',
                accuracy: null,
                region: region,
                source: 'Simulation EMA Forecast',
                note: 'Run python src/ml_forecasting.py to generate ML predictions',
                lastUpdated: new Date().toISOString()
            });
        }

        return NextResponse.json({
            predictions: [],
            model: model,
            accuracy: null,
            region: region,
            source: 'none',
            error: 'No predictions available. Run python main.py or python src/ml_forecasting.py first.',
            lastUpdated: new Date().toISOString()
        }, { status: 200 });

    } catch (error) {
        console.error('ML Predictions API Error:', error);
        return NextResponse.json({
            predictions: [],
            error: error.message,
            source: 'error',
            lastUpdated: new Date().toISOString()
        }, { status: 500 });
    }
}
